services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: C_backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/task_db"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: C_frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    build: ./nginx
    container_name: C_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend