services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: C_backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: C_frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - 5173:5173
# ... (le reste reste identique)

  nginx:
    build: ./nginx
    container_name: C_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

# Ici, on ne déclare que les volumes NOMMÉS (gérés par Docker)
volumes:
  postgres_data: