server {

    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1; #nécessaire pour maintenir des connexions persistantes, notamment pour le HMR (Hot Module Replacement) de Vite
        proxy_set_header Upgrade $http_upgrade; #?? permet de supporter les websocket / pour mettre a jour quand je modif mon code
        proxy_set_header Connection 'upgrade'; #?? permet de supporter les websocket / pour mettre a jour quand je modif mon code
        proxy_set_header Host $host; # transmet le nom d'hote au front
        proxy_cache_bypass $http_upgrade; # ne pas mettre en cache les requetes qui utilisent une connexion "upgrade" (websocket)
    }

    location /api {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host; # transmet le nom d'hote au back (quel domaine a ete appele)
        proxy_set_header X-Real-IP $remote_addr; # transmet l'addresse ip reel du visiteur au back (sinon ce serait tjs l'ip de intern du container nginx)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # pour toujours connaitre le trafique reel des ip (inutile car je suis sur le port 80)
                                         #ip_client, #proxy1_ip #proxy2_ip 
        
    }
}